doctrine:
    dbal:
        schema_filter: ~^(?!broadway_event)~ # this will ignore broadway event store table
        url: '%env(resolve:DATABASE_URL)%'
        driver:   pdo_mysql
        charset: utf8mb4
        server_version: '8.0'
        types:
          uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
          datetime_immutable: App\Infrastructure\Shared\Persistence\Doctrine\Types\DateTimeType

          # Auth
          user_id: App\Auth\Infrastructure\Types\UserIdType
          unique_email: App\Auth\Infrastructure\Types\UniqueEmailType
          email: App\Auth\Infrastructure\Types\EmailType
          hashed_password: App\Auth\Infrastructure\Types\HashedPasswordType

        mapping_types:
          uuid_binary: binary
          user_id: binary
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Auth:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Auth/Config/mapping'
                prefix: 'App\Auth'
                alias: Auth
            Infrastructure:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Config/mapping'
                prefix: 'App\Infrastructure'
                alias: Infrastructure
