framework:
    messenger:
        default_bus: messenger.bus.command
        failure_transport: failed

        buses:
            messenger.bus.command:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.query:
                default_middleware: false
                middleware:
                    - handle_message

            messenger.bus.event:
                default_middleware: allow_no_handlers

        transports:
            events:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    delay: 2000
                    max_retries: 5
                    multiplier: 2
                    max_delay: 0
                options:
                  table_name: 'messenger_events'

            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed"

        routing:
            'Broadway\Domain\DomainMessage': events
