version: '3.7'

services:

  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./etc/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/app/public:ro
    depends_on:
      - php

  code:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: php-dev
    volumes:
      - ./:/app:rw,delegated

  php:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: php-dev
    volumes:
      - ./:/app:rw,delegated
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
     - "./etc/ci/mysql:/etc/mysql/conf.d"
    tmpfs:
     - /var/lib/mysql/:rw,noexec,nosuid,size=600m
     - /tmp/:rw,noexec,nosuid,size=50m
    environment:
      - MYSQL_ROOT_PASSWORD=api
      - MYSQL_DATABASE=api

  redis:
    image: redis

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mysql
    command: mysql:3306
