# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  #elastic:
  #  hosts:
  #    - '%env(ELASTIC_HOST)%'

  #env(ELASTIC_HOST): 'elasticsearch:9200'
  env(DATABASE_URL): 'mysql://root:api@mysql:3306/api?serverVersion=8.0'

  exception_to_status:
    InvalidArgumentException: 400
    App\Auth\Domain\User\Exception\InvalidCredentialsException: 401
    App\Auth\Domain\User\Exception\ForbiddenException: 403
    App\Infrastructure\Shared\Persistence\ReadModel\Exception\NotFoundException: 404
    Broadway\Repository\AggregateNotFoundException: 404

services:
    # Needed since Since symfony/dependency-injection 5.1
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'

    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
          $eventSourcingBus: '@broadway.event_handling.event_bus'
          $eventSourcingStore: '@Broadway\EventStore\Dbal\DBALEventStore'
          $redis: '@snc_redis.default'

    _instanceof:
        App\Shared\Application\Command\CommandHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.command }

        App\Shared\Application\Query\QueryHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.query }

        App\Shared\Application\Event\EventHandlerInterface:
          public: true
          tags:
            - { name: messenger.message_handler, bus: messenger.bus.event }

        Broadway\EventHandling\EventListener:
          public: true
          tags:
              - { name: broadway.domain.event_listener }

    App\:
        resource: '../src/*'
        exclude: '../src/**/{Migrations,EventSubscriber}'

    App\Infrastructure\Shared\Bus\Command\MessengerCommandBus:
        arguments:
          - '@messenger.bus.command'

    App\Infrastructure\Shared\Bus\Query\MessengerQueryBus:
        arguments:
          - '@messenger.bus.query'

    App\Infrastructure\Shared\Bus\Event\MessengerEventBus:
        arguments:
          - '@messenger.bus.event'

    App\Auth\Domain\User\Repository\UserRepositoryInterface:
      '@App\Auth\Infrastructure\User\Repository\UserWriteDoctrineRepository'
      #'@App\Auth\Infrastructure\User\Repository\UserWriteEventRepository'

    ### Event Store

    Broadway\EventStore\Dbal\DBALEventStore:
        public: true
        arguments:
          - '@doctrine.dbal.default_connection'
          - '@broadway.serializer.payload'
          - '@broadway.serializer.metadata'
          - 'broadway_events'
          - true
          - '@broadway.uuid.converter'

    ### UI

    App\UI\Cli\Command\:
        resource: '../src/UI/Cli/Command'

    App\UI\Http\Rest\Controller\:
        resource: '../src/UI/Http/Rest/Controller/*'
        tags: [ 'controller.service_arguments' ]

    App\UI\Http\Web\Controller\:
        resource: '../src/UI/Http/Web/Controller/*'
        tags: [ 'controller.service_arguments' ]

    ### UI Listeners

    App\UI\Http\Rest\EventSubscriber\ExceptionSubscriber:
        arguments:
            - "%kernel.environment%"
            - "%exception_to_status%"
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    App\UI\Http\Rest\EventSubscriber\JsonBodyParserSubscriber:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 100 }
